dataset: "swat"

data_params:
  data_dir: "data/"
  group: "1-1"
  lookback: 5
  normalize: true
  spec_res: false

model_params:
  window_size: 4
  kernel_size: 7
  use_gatv2: true
  feat_gat_embed_dim: null
  time_gat_embed_dim: null
  gru_n_layers: 1
  gru_hid_dim: 300
  forecast_n_layers: 3
  forecast_hid_dim: 300
  recon_n_layers: 1
  recon_hid_dim: 300
  dropout: 0.3
  alpha: 0.2

train_params:
  n_epochs: 30
  batch_size: 264
  init_lr: 0.001
  device: "mps"
  n_workers: 0
  target_dims: null
  log_dir: "output"
  log_every_n_steps: 1
  ckpt_path: null
  test_size: 0.1
  val_size: 0.1
  clean: true # remove anomalies from training data
  interpolate_method: null

predictor_params:
  dataset: "custom"
  target_dims: null
  scale_scores: false
  level: 0.9999 
  q: 0.001
  dynamic_pot: false
  use_mov_av: false
  gamma: 0.8
  reg_level: 1
save_path: "saved_models/mtad_gat"
