dataset: "telco"

train_params:
  batch_size: 128
  n_epochs: 5
  val_size: 0.1
  weight_decay: 0.0
  device: "cpu"
  init_lr: 0.001

model_params:
  window_size: 15
  dim: 64
  out_layer_num: 1
  out_layer_inter_dim: 256
  topk: 5
  stride: 5

env_params:
  save_path_pattern: ""
  random_seed: 42
  report: "val"
  load_model_path: ""
  save_path: "msl"
